name: Update Citations

on:
  schedule:
    - cron: '0 0 * * *'  # 每天运行一次
  workflow_dispatch:      # 允许手动触发

permissions:
  contents: write        # 明确设置写入权限

jobs:
  update-citations:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'zilin-huang'  # 确保只在你的仓库中运行
    
    steps:
    - uses: actions/checkout@v3    # 使用与其他工作流相同的版本
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver_manager
    
    - name: Run update script
      run: python scripts/update_citations.py
    
    - name: Commit and push if changed
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add _data/citations.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update citations" && git push) 